# Generated by Django 4.2 on 2023-05-31 20:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre Género')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=70, verbose_name='Apellido')),
                ('nombre_artistico', models.CharField(max_length=70, null=True, verbose_name='Nombre artístico')),
                ('nacionalidad', django_countries.fields.CountryField(max_length=70, verbose_name='Nacionalidad')),
                ('foto', models.ImageField(null=True, upload_to='fotos_personas', verbose_name='Foto')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('biografia', models.TextField(max_length=300, verbose_name='Biografía')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('resumen', models.TextField(max_length=200, verbose_name='Resumen')),
                ('anio_realizacion', models.DateField(verbose_name='Año estreno')),
                ('duracion', models.DurationField()),
                ('puntuacion', models.FloatField(default=0, verbose_name='Puntuacion')),
                ('poster', models.ImageField(null=True, upload_to='posters_peliculas', verbose_name='Póster')),
                ('actor', models.ManyToManyField(related_name='actor', to='peliCura.persona')),
                ('director', models.ManyToManyField(related_name='director', to='peliCura.persona')),
                ('genero', models.ManyToManyField(to='peliCura.genero')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('E', 'escrito'), ('A', 'publicado'), ('C', 'censurado')], default='E', max_length=1, verbose_name='Estado')),
                ('_fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('descripcion', models.TextField(max_length=100, verbose_name='Comentario')),
                ('valoracion', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntaje')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peliCura.pelicula')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
