# Generated by Django 4.2 on 2023-05-31 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='_fecha',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='anio_nacimiento',
        ),
        migrations.AddField(
            model_name='comentario',
            name='%D-%m-%d %H-%M-%S',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-12-05', verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.CharField(choices=[('E', 'escrito'), ('A', 'publicado'), ('C', 'censurado')], default='E', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre usuario'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre Género'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='anio_realizacion',
            field=models.DateField(verbose_name='Año estreno'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters_peliculas', verbose_name='Póster'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='puntuacion',
            field=models.FloatField(default=0, verbose_name='Puntuacion'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='resumen',
            field=models.TextField(verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=70, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='biografia',
            field=models.TextField(max_length=300, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_personas', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(max_length=70, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=70, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_artistico',
            field=models.CharField(max_length=70, null=True, verbose_name='Nombre artístico'),
        ),
    ]
