# Generated by Django 4.2 on 2023-05-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nacimiento',
            new_name='anio_nacimiento',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters_peliculas'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_personas'),
        ),
    ]
