# Generated by Django 4.2 on 2023-05-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0002_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='resumen',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(default='Peli', max_length=300, verbose_name='Sinospis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_artistico',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombre artístico'),
        ),
    ]
