# Generated by Django 4.2 on 2023-05-31 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0002_remove_comentario__fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='%D-%m-%d %H-%M-%S',
        ),
        migrations.AddField(
            model_name='comentario',
            name='_fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
