# Generated by Django 4.2 on 2023-05-26 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0002_rename_nacimiento_persona_anio_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='_estado',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='valoracion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntaje'),
        ),
    ]
