# Generated by Django 4.2 on 2023-05-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0003_remove_comentario__d_m_d_h_m_s_comentario__fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nacionalidad',
        ),
    ]
