# Generated by Django 4.2 on 2023-05-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0003_remove_pelicula_resumen_pelicula_sinopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(max_length=500, verbose_name='Sinospis'),
        ),
    ]
