# Generated by Django 4.2 on 2023-05-31 17:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0004_remove_persona_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=django_countries.fields.CountryField(default='Argentina', max_length=70, verbose_name='Nacionalidad'),
            preserve_default=False,
        ),
    ]
