# Generated by Django 4.2 on 2023-06-01 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0004_alter_pelicula_sinopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='_fecha',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1240)]),
        ),
    ]
