# Generated by Django 4.2 on 2023-06-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0005_rename__fecha_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliCura.pelicula'),
        ),
    ]
