# Generated by Django 4.2 on 2023-06-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0006_alter_comentario_pelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='puntuacion',
        ),
    ]
