# Generated by Django 4.2 on 2023-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliCura', '0007_remove_pelicula_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='puntuacion',
            field=models.FloatField(default=0, verbose_name='Puntuacion'),
        ),
    ]
