# Generated by Django 4.2 on 2023-04-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.TextField(null=True),
        ),
    ]
