# Generated by Django 4.2 on 2023-04-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_libro_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(default='0000')),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='isbn13',
        ),
        migrations.AddField(
            model_name='libro',
            name='anio',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default='fotocopiado', max_length=100),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.IntegerField(default='0000000000000'),
        ),
    ]
