# Generated by Django 4.2 on 2023-04-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_autor_remove_libro_isbn13_libro_anio_libro_editorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=100),
        ),
    ]
