# Generated by Django 4.2 on 2023-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_copia_lector_prestamo_autor_libro_libro_tipo_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(default='--'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='anio',
            field=models.IntegerField(default='--'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.IntegerField(default='--'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(default='--', max_length=100),
        ),
    ]
